services:
  openresty:
    image: openresty/openresty:1.21.4.1-focal
    container_name: openresty
    restart: always
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./openresty/conf.d:/etc/nginx/conf.d:ro
      - ./openresty/ssl:/etc/openresty/ssl:ro
      - ./certbot/www:/var/www/certbot:ro # 用于ACME http-01 质询
    networks:
      mynet:
        ipv4_address: 172.28.0.10

networks:
  mynet:
    external: true